fix undefined txs otel error
rainlanguage/arb-bot pull request #131
Opened 2024-06-20 20:37 UTC by rouzwelt

## Motivation
fix `Cannot destructure property 'txs' of '(intermediate value)' as it is undefined.` error.
resolves #133 

## Solution
dont return undefined on early resolve when no orders are found but return correct object

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-06-21 11:29 UTC, thedavidmeister requested changes

2024-06-21 11:29 UTC, thedavidmeister commented on arb-bot.js
> +                const result = await arbRound(tracer, roundCtx, options, lastError);
is there a way to test the issue this is fixing?

2024-06-22 10:47 UTC, hardyjosh approved these changes

2024-06-23 12:44 UTC, hardyjosh approved these changes

2024-06-23 12:44 UTC, merged